### ISSUE TITLE
disable IPv6

### ISSUE THREAD

**Issue by acoul** [nidebr/as-stats-gui#1]
Greetings, 

This is mainly a feature request.

Having an option to disable IPv6 would be handy for some IPv4 only setups.

Thank you for offering as-stats-gui  to the open-source community.

**Comment by nidebr** [comment]
Hi Alexandros,

Thanks for you message.

You can disable IPv6 on config.inc file with this option : $showv6 = false;

All options are same that orignal GUI of AS-Stats.

BR

**Comment by acoul** [comment]
thank you, closing this ticket.
