### ISSUE TITLE
asstats_week.txt & asstats_month.txt

### ISSUE THREAD

**Issue by dnk2009** [nidebr/as-stats-gui#12]
hi,
please tell me. what are these structures responsible for "config.inc". I didn't find any such paths in the" www" folder

$top_intervals[] = array(
'hours' => 7*24,
'statsfile' => '/data/as-stats/asstats_week.txt',
'label' => '1 week'
);
$top_intervals[] = array(
'hours' => 30*24,
'statsfile' => '/data/as-stats/asstats_month.txt',
'label' => '30 days'
);

**Comment by dnk2009** [comment]
I am change path. 
Сreate tasks in cron:
1 1     * * *   root    /opt/AS-Stats/bin/rrd-extractstats.pl /opt/AS-Stats/rrd/ /opt/AS-Stats/conf/knownlinks /opt/AS-Stats/asstats/asstats_week.txt 168
1 4     * * *   root    /opt/AS-Stats/bin/rrd-extractstats.pl /opt/AS-Stats/rrd/ /opt/AS-Stats/conf/knownlinks /opt/AS-Stats/asstats/asstats_month.txt 720

How to make links to them in the web interface?

by applying these parameters to the address:" index.php?numhours=720&n=20", shows daily download parameters.

**Comment by nidebr** [comment]
Hi,

I'm not sur if I understand your question.

If your run your cron like your second comment, configure your config.inc like this : 

$top_intervals[] = array(
'hours' => 724,
'statsfile' => '/opt/AS-Stats/asstats/asstats_week.txt',
'label' => '1 week'
);
$top_intervals[] = array(
'hours' => 3024,
'statsfile' => '/opt/AS-Stats/asstats/asstats_month.txt',
'label' => '30 days'
);

br

**Comment by dnk2009** [comment]
thanks, man. I didn't notice that this piece of config is commented.
