### ISSUE TITLE
data gathered, top20 counters changing, but graphs "blank" (the image not generated)

### ISSUE THREAD

**Issue by rekeds** [nidebr/as-stats-gui#15]
Hi! Maybe you could share tips - where to look further, if you have the time. Thank you!
The Picture  links are empty, like the "url' is not resolved/timed out in "Home" view, and in History (if clicked one of the "empty graph links").

Is it OK if I import only V4 data? (v4 data has some counters, v6 data is 0)
example:
```
In the last 24 hours
IPv4: ~ 230.17 GB in / 314.36 GB
IPv6: ~ 0 bytes in / 0 bytes
```

Maybe you could suggest what to double check? Nginx isn't giving any errors in error.log, but the graphs stay empty.
Data is being processed as the top20 kept changing and ASN is showing some data In/Out.
Only the graphs are not generated.
If I open the gengraph directly: gengraph.php (without Post prameters) -> returns message that "Invalid ASN".

from the "installAS-Stats.sh" script, I hope (i really tried to check everything that I got it correctly from the list):
`yum install -y httpd httpd-devel php php-gd phpimap php-ldap php-odbc php-pear php-xml php-xmlrpc php-mcrypt curl curl-devel perl-libwwwperl libxml2 php-mbstring rrdtool perl-rrdtool`
My install is on debian, I searched for alternatives on Debian, instead of httpd (apache), I have nginx on that server.
(from php info file I believe I have the packages)

nginx.access logs entry (one of several):
`10.159.55.22 - - [03/Dec/2020:20:05:40 +0200] "GET /gengraph.php?v=6&as=20446&peerusage=0&dname=AS20446%20-%20Highwinds%20Network%20Group%2C%20Inc.%2CUS%20-%20IPV6&start=1606932339&end=1607018739&width=600&height=220&nolegend=1 HTTP/1.1" 200 5 "http://10.253.0.1:81/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"`

I've set the memory limit to 512M. (verified in phpinfo)

Don't know where to look for debug more. :(

Thanks to anybody if you have ideas!

**Comment by nidebr** [comment]
Hi,

For your empty graph, check rights of ./rrd directory, check if your www-data (or www) account access to files.

For IPv6 : 

in config.inc, set to false this option : "$showv6 = true;"

BR

**Comment by rekeds** [comment]
thank you, that was it. 
updated user permissions. sorry for bothering! 

Thank you for your time and have a great weekend!
