### ISSUE TITLE
SQLite3 error no such table

### ISSUE THREAD

**Issue by ovsepdev** [nidebr/as-stats-gui#17]
Hi!
I have a problem starting the web server. In  the errors logs apache2 shows:
[Sat Sep 11 00: 09: 49.700320 2021] [php7: warn] [pid 3002099] [client 10.10.10.4:41349] PHP Warning: SQLite3 :: query (): Unable to prepare statement: 1, no such table: stats in /opt/asstats/www/func.inc on line 125

[Sat Sep 11 00: 09: 49.700386 2021] [php7: error] [pid 3002099] [client 10.10.10.4:41349] PHP Fatal error: Uncaught Error: Call to a member function fetchArray () on bool in / opt / asstats /www/func.inc:127\nStack trace: \ n # 0 /opt/asstats/www/index.php(25): getasstats_top () \ n # 1 {main} \ n thrown in / opt / asstats / www /func.inc on line 127

Installed php7.4 and package php7.4-sqlite3

What could be the problem?
Thanks.

**Comment by nidebr** [comment]
Hi,
Please check this issue 
 https://github.com/nidebr/as-stats-gui/issues/14

BR

**Comment by ovsepdev** [comment]
I tried this but it didn't work for me.
sqlite3 module for php is included.
There are no spaces or "-" in knownlinks.
I have no idea what could be the reason.

**Comment by nidebr** [comment]
Its work with original UI ?

**Comment by ovsepdev** [comment]
No.

**apache2 error log for original UI:**

[Sat Sep 11 08:57:02.790974 2021] [php7:warn] [pid 3068485] [client 10.10.10.4:39077] PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, no such table: stats in /opt/asstats/www/func.inc on line 121

[Sat Sep 11 08:57:02.791063 2021] [php7:error] [pid 3068485] [client 10.10.10.4:39077] PHP Fatal error:  Uncaught Error: Call to a member function fetchArray() on bool in /opt/asstats/www/func.inc:123\nStack trace:\n#0 /opt/asstats/www/top.php(42): getasstats_top()\n#1 {main}\n  thrown in /opt/asstats/www/func.inc on line 123

**my knownlinks file:**

```
cat /opt/asstats/conf/knownlinks 
# Router IP             SNMP ifindex[/VLAN]     tag                             description             color   samplingrate
# note: tabs must be used to separate fields (not spaces)
# max. length for tag is 12 characters; allowed characters: a-z A-Z 0-9 _
# sampling rate can be separate for in/out by specifying <in>/<out> rates.
64.23.46.31             339199755                               global                  Uplink1         A6CEE3  20000
```

**my config.inc:**

$rrdpath = "/opt/asstats/myasn";
$daystatsfile = "/opt/asstats/myasn/asstats_day.txt";
$rrdtool = "/usr/bin/rrdtool";

$daypeerstatsfile = "/opt/asstats/myasn/peerasstats_day.txt";
$showpeeras = false;

$asinfofile = "asinfo.txt";
$knownlinksfile = "/opt/asstats/conf/knownlinks";
$outispositive = true;
$show95th = true;

**my apache2 config file:**

<VirtualHost *:8080>
        ServerName asstats.example.com
        DocumentRoot /opt/asstats/www/
        <Directory "/opt/asstats/www/">
        AuthType Basic
        AuthName "Restricted Content"
        AuthUserFile /etc/apache2/.htpasswd
        Require valid-user
        DirectoryIndex index.php
        </Directory>
</VirtualHost>

Ubuntu version - 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
PHP version - PHP 7.4.3 (cli) (built: Aug 13 2021 05:39:12) ( NTS )
SQLite3 version- 3.31.1
