### ISSUE TITLE
size and format of graphs

### ISSUE THREAD

**Issue by acoul** [nidebr/as-stats-gui#2]
I believe this is a feature request too.

It would be nice to be able to adjust number of graphs per row and possible their relative size. Some of my efforts can be found [here]( http://dev.ozo.com/as-stats/)

Edit: size of the graphs can be adjusted on config_defaults.inc

**Comment by nidebr** [comment]
Hi Alexandros,

Yes, as for the original GUI the size of the graphs can be adjusted on config_defaults.inc file.

And for the numbers of graphs, it's in config.inc file with the variable $ntop.

I very happy that you test this GUI ;)

BR

**Comment by acoul** [comment]
thank you BR for your quick reply. It's an eye-candy gui .

closing this ticket.

**Comment by acoul** [comment]
thank you BR for your quick reply. It's an eye-candy gui .

closing this ticket.
