### ISSUE TITLE
as-info updated ?

### ISSUE THREAD

**Issue by nicoonline** [nidebr/as-stats-gui#22]
Hello,

I have downloaded the last asinfo.txt
Do you have any mechanism to update this file with the real AS Name ?

**Comment by nidebr** [comment]
Hello,

See on AS-Stats Repo, this script : 
https://github.com/manuelkasper/AS-Stats/blob/master/contrib/generate-asinfo.py

BR

**Comment by nicoonline** [comment]
Hello,

I tried this but ending after AS2929

2929    S       S       US

File asinfo.txt not changed so no update needed
[root@ns3 contrib]# (echo begin; echo verbose; for i in `seq 1 65535`; do echo "AS$i"; done; echo end) | nc whois.cymru.com 43 | ./generate-asinfo.py > asinfo.txt

**Comment by nidebr** [comment]
Hello,

its work on my side.
but you can create one issue on original repo of AS-Stats.

i uploaded a fresh update of asinfo.txt on my repo, if you want.

BR.

**Comment by nicoonline** [comment]
Thanks !! ;)
