### ISSUE TITLE
upstream changes

### ISSUE THREAD

**Issue by acoul** [nidebr/as-stats-gui#3]
upstream commit [d6c4c0ff951a6d8bf881177a4fa41245c6acc1dd](https://github.com/manuelkasper/AS-Stats/commit/d6c4c0ff951a6d8bf881177a4fa41245c6acc1dd#diff-4eae35f1b35977a00ebd8086c259d4c9) brakes as-stats-gui

**Comment by nidebr** [comment]
@acoul, I perform update code to include this update (SQLlite stats file)

**Comment by acoul** [comment]
[works wonderfully](http://dev.ozo.com/as-stats/)
