### ISSUE TITLE
Missing argument when menu() function is called from history.php

### ISSUE THREAD

**Issue by dpiekacz** [nidebr/as-stats-gui#4]
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function menu(), 0 passed in /opt/as-stats-gui/history.php on line 72 and exactly 1 expected in /opt/as-stats-gui/func.inc:256 Stack trace:
 #0 /opt/as-stats-gui/history.php(72): menu() #1 {main}   thrown in /opt/as-stats-gui/func.inc on line 256

It will be the same story for asset.php, linkusage.php and sample-blank.php

Small patch included as an attachment. Tested with the latest GIT version.
[as-stats-gui_patch.txt](https://github.com/nidebr/as-stats-gui/files/918958/as-stats-gui_patch.txt)

.

**Comment by nidebr** [comment]
Hi,

Thanks for your patch, I just commit it.

BR.
