### ISSUE TITLE
asstats_day.txt Issue ?

### ISSUE THREAD

**Issue by Jpc42** [nidebr/as-stats-gui#5]
Hi

i want test your gui, but if i pout the good path of:
$daystatsfile = "/var/www/as-stats/asstats_day.txt";
in config.inc, i have a blank screen and in logs:

PHP Warning:  SQLite3::query(): Unable to prepare statement: 26, file is encrypted or is not a database in /var/www/as-stats/www/func.inc on line 101

PHP Fatal error:  Call to a member function fetchArray() on a non-object in /var/www/as-stats/www/func.inc on line 103

do you know this errors ?

regards

**Comment by nidebr** [comment]
Hi Jpc42,
Last update work only with last update of as-stats (with database sql-lite3).
Show this update : https://github.com/manuelkasper/AS-Stats/commit/d6c4c0ff951a6d8bf881177a4fa41245c6acc1dd

If you want use old release for flat file database, download this update of as-stats-gui : 
https://github.com/nidebr/as-stats-gui/archive/d2cd398eaf7ed889d71814e4
b9aad6475a68a8b7.zip

BR

**Comment by sysblade** [comment]
Is there any new issues with the last versions of both ?
Using the legacy web UI from the as-stats project works but I'm getting SQLite errors from as-stats-gui (Columns names are not matching)

```
sqlite> .schema
CREATE TABLE stats("asn" int, "clancy-zayo_in" int, "clancy-zayo_out" int, "clancy-zayo_v6_in" int, "clancy-zayo_v6_out" int, "amico-ielo_in" int, "amico-ielo_out" int, "amico-ielo_v6_in" int, "amico-ielo_v6_out" int);
sqlite> ^C

PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, no such column: amico in /data/as-stats/www/func.inc on line 117

```

**Comment by nidebr** [comment]
Hi, 

Please read that : https://github.com/manuelkasper/AS-Stats#installation

"a short "tag" (12 chars max., a-z A-Z 0-9 _ only) that will be used internally (e.g. for RRD DS names)"

I think that your problem is that ... 

BR

Please open your own issue, I think isn't same issue.
