### ISSUE TITLE
Dirty code

### ISSUE THREAD

**Issue by Exagone313** [nidebr/as-stats-gui#7]
Hi,

The whole code is dirty, I easily found XSS vulnerabilities (see #6).
To make the code properly maintainable, the least is to have layout (HTML, templates) separated from computation, but each kind of "component" should be clearly separated (abstraction). Also, code is written with weird PHP practices (like `@$var`, `==` instead of `===` when inappropriate, etc...).

If someone is willing to rewrite everything, users would surely appreciate.

**Comment by nidebr** [comment]
Hi,

A few months ago I started working on a new release based on a framework and redo code a little cleaner, but I have not had time to really put back, I must look to that.

Thank you for your contribution.

**Comment by dermalikmann** [comment]
Hey there!
Thank you very much for the new UI! Just wanted to make an addition:
If you are currently working on a redo I wanted to ask if you could stick more to the original template of AdminLTE. I personally think that it's more appealing to the eye. It's not that the current color scheme is ugly after all, but what's the point of using a template when only very few of its aspects are used? :sweat_smile: 
But as I said: It's just a personal note.

Again thank you for your work.

Oh and by the way: If you are working on a redo, just push your changes to another branch. I would love to give a helping hand if I can ^^
