### ISSUE TITLE
Check for valid knownlinks in gengraph too restrictive, missing _

### ISSUE THREAD

**Issue by MadDog2K** [nidebr/as-stats-gui#8]
Hi,

We have knownlinks that have a tag like :

Abcd_EFGH567
Mnop_QRST123

Since the latest commits, a new check in gengraph appeared :

```php
-       foreach(explode(',', $_GET['selected_links']) as $tag){
+    foreach(explode(',', $_GET['selected_links']) as $tag){
+        if (preg_match('/[^a-zA-Z0-9]/', $tag))
+            continue;
```

This regular expression does not match our knownlinks tags due to the '_' character, and hence breaks the graphs.

The latest AS-stats master states :

"max. length for tag is 12 characters; allowed characters: a-z A-Z 0-9 _"

So '_' should be added to the regular expression as well :)

**Comment by nidebr** [comment]
@MadDog2K, sorry for delay ;), you right. fixed in last commit.
