### ISSUE TITLE
View IX-Stats error

### ISSUE THREAD

**Issue by chrisvanmeer** [nidebr/as-stats-gui#9]
When clicking on "View IX Stats", you receive the error in your log file:

`PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/html/as-stats/lib/class/peeringdb.php:87\nStack trace:\n#0 /var/www/html/as-stats/ix.php(119): PeeringDB->GetIXASN(<IX ASN>)\n#1 {main}\n  thrown in /var/www/html/as-stats/lib/class/peeringdb.php on line 87`

I traced the error back to lib/class/peeringdb.php line 82.
Replacing

`$return = "";`

With

`$return = [];`

Resolved the issues for me.

**Comment by fjbf** [comment]
Please, change line 82 in peeringdb.php from:

$return = "";

to:

$return = array();

**Comment by nidebr** [comment]
fixed on commit [https://github.com/nidebr/as-stats-gui/commit/23fa0de20f7e34acbe4b1a7d97dd247753cb3c0e](url)
